saveeeeeeeee

diff --git a/arch32-install b/arch32-install
--- a/arch32-install
+++ b/arch32-install
@@ -1140,8 +1140,7 @@ setup_resolvconf()
   then
    echo "nameserver 8.8.8.8" >> /mnt/etc/resolv.conf
    chroot /mnt curl -s $ASCII || {
-    err "No network connection. Aborting"; }
-    exit $FAILURE
+    err "No network connection. Aborting"; exit $FAILURE; }
   fi
   
   else
